- name: Gathering facts about ec2-instances
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
  - credentials.vault

  roles:
  - { role: bastion }

- name: Configure web servers
  hosts: web_servers
  become: true
  roles:
  - {role: tomcat}

 
