# tasks file for tomcat

- name: ADD TOMCAT GROUP
  group: 
    name: "{{tomcat_group}}"

- name: ADD TOMCAT USER
  user:
    name: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    home: /opt/tomcat
    system: yes

- name: DOWNLOADING AND UNARCHIVE TOMCAT 
  unarchive:
    src: "{{ tomcat_url }}" 
    dest: /opt/tomcat
    owner: "{{tomcat_user}}" 
    group: "{{tomcat_group}}"
    creates: /opt/tomcat/apache-tomcat-{{tomcat_version}}/
    remote_src: yes 
  become_user: "{{tomcat_user}}"

- name: RENAME FOLDER
  shell: mv /opt/tomcat/apache-tomcat-{{tomcat_version}} /opt/tomcat/{{tomcat_version}}
  args: 
    creates: /opt/tomcat/{{tomcat_version}}
  become_user: "{{tomcat_user}}"

- name: CREATE SYMLINK
  file: 
    src: /opt/tomcat/{{tomcat_version}}
    dest: "{{tomcat_home}}"
    state: link
    force: yes
  become_user: "{{tomcat_user}}"
  notify: RESTART TOMCAT

- name: COPYING INIT SCRIPT
  template: 
    src: tomcat-init.j2
    dest: /etc/init.d/tomcat
    mode: 0755 
  notify: RESTART TOMCAT

- name: COPYING TOMCAT-USERS
  template: 
    src: tomcat-users.j2
    dest: /opt/tomcat/{{tomcat_version}}/conf/tomcat-users.xml
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0755
  become_user: "{{tomcat_user}}" 
  notify: RESTART TOMCAT

- name: COPYING CONTEXT.xml
  template: 
    src: context.j2
    dest: /opt/tomcat/{{tomcat_version}}//webapps/manager/META-INF/context.xml 
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0755 
  become_user: "{{tomcat_user}}" 
  notify: RESTART TOMCAT

- name: start tomcat
  service: 
    name: tomcat
    state: started
  become_user: "{{tomcat_user}}"
