# tasks file for tomcat

- name: ADD GROUP
  group: name="{{tomcat_group}}" state=present 
  become: yes
  become_user: root

- name: ADD USER
  become: yes
  become_user: root
  user: name="{{tomcat_user}}" group="{{tomcat_group}}" home=/opt/tomcat
     

- name: DOWNLOADING AND UNARCHIVE TOMCAT 
  unarchive: src="{{ tomcat_url['version'] }}" dest=/opt/tomcat owner="{{tomcat_user}}" group="{{tomcat_group}}" remote_src=true creates=/opt/tomcat/apache-tomcat-{{tomcat_version}}/ 
  become: yes
  become_user: "{{tomcat_user}}"

- name: RENAME FOLDER
  shell: mv /opt/tomcat/apache-tomcat-{{tomcat_version}} /opt/tomcat/{{tomcat_version}} creates=/opt/tomcat/{{tomcat_version}}
  become: yes
  become_user: "{{tomcat_user}}"

- name: CREATE SYMLINK
  file: src=/opt/tomcat/{{tomcat_version}} dest="{{tomcat_home}}" state=link force=yes
  become: yes
  become_user: "{{tomcat_user}}"
  notify: RESTART TOMCAT


- name: COPYING INIT SCRIPT
  template : src=tomcat-init.j2 dest=/etc/init.d/tomcat owner=root group=root mode=0755 
  become: yes
  become_user: root 
  notify: RESTART TOMCAT

- name: COPYING TOMCAT-USERS
  template : src=tomcat-users.j2 dest=/opt/tomcat/{{tomcat_version}}/conf/tomcat-users.xml owner="{{tomcat_user}}" group="{{tomcat_group}}" mode=0755 
  become: yes
  become_user: "{{tomcat_user}}" 
  notify: RESTART TOMCAT

- name: COPYING CONTECT.xml
  template : src=context.j2 dest=/opt/tomcat/{{tomcat_version}}//webapps/manager/META-INF/context.xml owner="{{tomcat_user}}" group="{{tomcat_group}}" mode=0755 
  become: yes
  become_user: "{{tomcat_user}}" 
  notify: RESTART TOMCAT

- name: start tomcat
  service: name=tomcat state=started
  become: yes
  become_user: "{{tomcat_user}}"
